### ISSUE TITLE
tokenManager sessionStorage doesnt work, can not save token in seesionStorage

### ISSUE THREAD

**Issue by mwx1993** [okta/okta-auth-js#342] opened 2020-03-03 21:50 UTC
Hello guys,
I would like to save the token in sessionStorage, I followed the document by add tokenManager storage in config, however the token is still saved in localStorage.

This is what I did: 
var config = {
    url: 'https://{yourOktaDomain}',
    // some other settings
    tokenManager: {
      storage: 'sessionStorage'
    }
};

and I am on version 2.13.2

Please advice how to properly save the token data in sessionStorage instead of localStorage. 
Thanks!

**Comment by aarongranick-okta** [comment] 2020-03-04 03:28
Hi @mwx1993,

The feature works just as you describe. I think there must be some other issue that is causing it to use a default TokenManager configuration. Are you able to debug through the code to see the config when TokenManager is constructed? This would be a good point to inspect in the debugger: https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/TokenManager.js#L206

Our module includes source maps. If you are using webpack to build your app, the `source-map-loader` plugin will help with debugging through our code: https://webpack.js.org/loaders/source-map-loader/ 

If debugging is not an option or does not clear up the issue, we may be able to help you diagnose the problem if you can post a larger portion of your application source.

**Comment by swiftone** [comment] 2020-03-20 20:11
Closing as unable to reproduce - feel free to reopen with additional details

**Closed by swiftone** 2020-03-20 20:11 UTC
Labels: awaiting-response, requires-reproduce

**Comment by sdtacoma** [comment] 2021-04-19 21:16
Were you ever able to figure out what the issue is/was?

**Comment by mwx1993** [comment] 2021-04-20 01:35
Hi @sdtacoma , unfortunately I didn't dig deeper on this solution because our team decide to move to another tool right after I raised this issue. Hope you will find the answer from their reply or maybe open another new issue for further support. Good luck!
