### ISSUE TITLE
The audience [my_id_ppd] does not match [my_id_ppd]

### ISSUE THREAD

**Issue by Mehdi-Morouche** [okta/okta-auth-js#225] opened 2019-07-08 15:32 UTC
Hello,

I have this issue on the oktaAuth.token.parseFromUrl() method.
The client_id and the client_id pre-registered are identical.

Thank you,

**Comment by swiftone** [comment] 2019-07-10 21:55
Hi @Mehdi-Morouche - That is not an error we've gotten any reports about.

The first idea would be to check the client id carefully - they often match in starting and ending characters but differ in the middle (I've lost a painful amount of time skimming over values that looked identical only to turn out to not be).  

If that's not the problem, if you could give a snippet of code (no need to include your client id, just something that we can use to try and reproduce with our own clients), that could help.

**Comment by Mehdi-Morouche** [comment] 2019-07-11 13:42
I checked the client_id and its not the problem.
I have this login method :
```
login() {
        // Launches the login redirect
       this.oktaAuth.token.getWithRedirect({
           responseType: ['token', 'id_token'],
           scopes: ['openid', 'profile']
       }).catch(err => console.log('error', err));
    }
```

And this one to handle the redirect :
```
handleAuthentication() {
       this.oktaAuth.token.parseFromUrl().then(tokens => {
            tokens.forEach(token => {
                if (token.idToken) {
                    this.oktaAuth.tokenManager.add('idToken', token);
                }
                if (token.accessToken) {
                    this.oktaAuth.tokenManager.add('accessToken', token);
                }
            });
        }).catch(err => console.log('error token', err));
```

This is the error : 
<img width="1050" alt="error" src="https://user-images.githubusercontent.com/18697858/61055460-d1929080-a3f1-11e9-9cca-0e6c1ddf8b62.png">

**Comment by noinarisak** [comment] 2019-12-05 19:58
Hi @Mehdi-Morouche, I ran into the same issue today. Make sure that your `Issuer` or OKTA_ORG_URL doesn't have extra `/`.  In my case my environment variable had a trailing `/`.

For example my error was this:
```
The issuer [https://dev-XXXXXX.okta.com/oauth2/default] does not match [https://dev-XXXXXX.okta.com//oauth2/default] 
```

There was extra `/` in `https://dev-XXXXXX.okta.com//oauth2/default`

Hope that helps.

**Comment by aarongranick-okta** [comment] 2019-12-09 21:53
@Mehdi-Morouche We have not been able to duplicate this, but we hope that we can resolve this issue. 

Can you provide more information on your configuration? Specifically:
- what is your `issuer` ?
- what type of app is this (Web, SPA) ?
- what version of `okta-auth-js` are you using?

Thanks in advance.

**Comment by swiftone** [comment] 2020-01-06 21:03
Closing as it seems to be a configuration issue.  If this continues to be a problem, feel free to reopen with more details.

**Closed by swiftone** 2020-01-06 21:03 UTC
Labels: awaiting-response, bug
