### ISSUE TITLE
Min version of the library uses the 'class' keyword which cannot be polyfilled

### ISSUE THREAD

**Issue by meh-uk** [okta/okta-auth-js#841] opened 2021-06-28 08:26 UTC
The 5.1.1 version of the library uses the class keyword in the minified version which cannot be polyfilled for IE, can we remove this so IE can be supported?

**Comment by meh-uk** [comment] 2021-06-28 08:27
The 5.1.1 version of the library uses the class keyword in the minified version which cannot be polyfilled for IE, can we remove this so IE can be supported?

**Comment by arvindkrishnakumar-okta** [comment] 2021-06-28 17:35
@meh-uk Thanks for posting!

@aarongranick-okta @shuowu-okta can you assist with this?

**Comment by aarongranick-okta** [comment] 2021-06-29 00:59
@meh-uk thanks for the report. We have confirmed the problem and created an internal ref: OKTA-408169
We will get this fixed ASAP

**Comment by meh-uk** [comment] 2021-06-30 08:23
Thanks!

**Comment by shuowu** [comment] 2021-07-19 15:04
@meh-uk The issue is fixed and released in version 5.2.2. Closing the issue, feel free to re-open it if the issue still exists.

**Closed by shuowu** 2021-07-19 15:04 UTC
