### ISSUE TITLE
Okta redirects to implicit callback with blank screen after a while

### ISSUE THREAD

**Issue by dustin-rcg** [okta/okta-auth-js#856] opened 2021-07-09 21:44 UTC
We have an app that was working before we upgraded. Our new versions are

@okta/okta-auth-js version "5.2.1"
@okta/okta-react version "6.0.0"
react version "17.0.2"

The app loads fine, but after some time (maybe 30-60 minutes) the screen appears blanks white.  We see in the javascript console that the app has automatically navigated to the implicit callback URL:
```
Navigated to http://localhost:3003/implicit/callback?code=[snip]&state=[snip]
```
Just prior to that console entry, we see a couple of these entries:
```
react_devtools_backend.js:2560 [okta-auth-sdk] WARN: Use setTokens() instead if you want to add a set of tokens at same time.
It prevents current tab from emitting unnecessary StorageEvent,
which may cause false-positive authState change cross tabs.
```

I am not sure whether this is due to autoRenew behavior. This is the code for our App component:

```
import { ApolloProvider } from "@apollo/client";
import { OktaAuth, toRelativeUrl } from "@okta/okta-auth-js";
import { LoginCallback, SecureRoute, Security } from "@okta/okta-react";
import ApolloClient from "apollo-boost";
import React, { useEffect, useState } from "react";
import { hot } from "react-hot-loader/root";
import { Provider } from "react-redux";
import { Route, Router, Switch } from "react-router-dom";
import getAuth from "Services/auth";
import history from "Services/history";
import { store } from "../stores/store";
import cache from "./configureApolloCache";
[snip]
import { get } from "Services/proxy_service";
import * as Sentry from "@sentry/react";

interface Services {
  auth: OktaAuth;
  client: ApolloClient<unknown>;
}

const App = () => {
  const restoreOriginalUri = (_oktaAuth: OktaAuth, originalUri: string) => {
    window.history.replaceState(
      null,
      "",
      toRelativeUrl(originalUri, window.location.origin)
    );
  };

  const [services, setServices] = useState<Services>();

  useEffect(() => {
    get("/config").then((result: any) => {
      const g = global as any;
      [snip setting globals]

      const auth = getAuth();
      const client = new ApolloClient({
        uri: (global as any).RCG_GRAPHQL_URI,
        request: async (operation) => {
          const token = auth.getAccessToken();
          operation.setContext({
            headers: {
              authorization: `Bearer ${token}`,
            },
          });
        },
        cache: cache as any,
        resolvers: {},
      });
      setServices({
        auth,
        client,
      });

      if (g.SENTRY_DSN) {
        Sentry.init({
          dsn: `https://${g.SENTRY_DSN}`,
          environment: g.SENTRY_ENVIRONMENT,
          release: g.SENTRY_RELEASE,
          beforeSend(event) {
            if (
              !["dev", "staging", "production", "test"].includes(
                event.environment!
              )
            ) {
              return null;
            }
            return event;
          },
        });
      }
    });
  }, []);

  // we still need to wait for config to be loaded to load the inside here

  return !services ? null : (
    <Security oktaAuth={services.auth} restoreOriginalUri={restoreOriginalUri}>
      <ApolloProvider client={services.client as any}>
        <Provider store={store}>
          <Router history={history}>
            <Switch>
              <Route path="/implicit/callback" component={LoginCallback} />
              <SecureRoute path="/impact-sd">
                <ImpactSD />
              </SecureRoute>
              <SecureRoute path="/" component={MercuryApp} />
            </Switch>
          </Router>
        </Provider>
      </ApolloProvider>
    </Security>
  );
};

App.displayName = "App";

export default hot(App);
```

services/auth.js
```
import { OktaAuth } from "@okta/okta-auth-js";

export default () => {
  const { OKTA_CLIENT_ID, OKTA_ISSUER }: any = global;
  if (!OKTA_ISSUER) throw new Error("get Auth called before config loaded");

  return new OktaAuth({
    issuer: OKTA_ISSUER,
    clientId: OKTA_CLIENT_ID,
    pkce: true,
    redirectUri: `${window.location.origin}/implicit/callback`,
  });
};
```

**Comment by MikeMondragon-okta** [comment] 2021-07-09 22:37
Hi @dustin-rcg I'll see if I can find some help with this.

**Comment by shuowu** [comment] 2021-07-09 23:31
@dustin-rcg I think your assumption is correct, it's caused by token auto renew, we'll prioritize the issue and investigate on the issue. 

Internal Ref: OKTA-410934

**Comment by duggantRC** [comment] 2021-07-14 14:10
Following up on this, has there been any progress?

**Comment by shuowu** [comment] 2021-07-14 15:09
@dustin-rcg We have prioritized the issue, a patch release will come soon. 

The cause is when idToken and accessToken expire at almost the same time, a false-positive authState.isAuthenticated status will be emitted during token auto renew process.  

A workaround is to add an [transformAuthState](https://github.com/okta/okta-auth-js#transformauthstate) option to evaluate authState.isAuthenticated based on `accessToken || idToken` instead of the default `&&` behavior.

```
return new OktaAuth({
  issuer: OKTA_ISSUER,
  clientId: OKTA_CLIENT_ID,
  pkce: true,
  redirectUri: `${window.location.origin}/implicit/callback`,

  // the workaround config, it can be removed when the patch is released
  transformAuthState: (oktaAuth, authState) => {
    const { accessToken, idToken } = authState;
    authState.isAuthenticated = accessToken || idToken;
    return authState;
  }
});
```

**Comment by shuowu-okta** [comment] 2021-07-22 20:04
This issue is fixed in [5.2.3](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.2.3) patch. Closing this issue, feel free to re-open if the issue still exist.

**Closed by shuowu-okta** 2021-07-22 20:04 UTC

**Comment by OwenVey** [comment] 2021-07-30 17:54
Still seeing this issue in 5.2.3. After approx 30 min when the token expires when trying to go to a route i'll see the ```[okta-auth-sdk] WARN: Use setTokens() instead if you want to add a set of tokens at same time.``` warning in my console and have to refresh the page to fix the issue.

**Comment by shuowu-okta** [comment] 2021-07-30 18:31
@OwenVey v5.2.3 fixes issue for active tokens auto renew flow, I saw you mentioned `when trying to go to a route` in your comment, have you set `autoRenew: false` (https://github.com/okta/okta-auth-js#autorenew) in your config, and calls `authClient.isAuthenticated` in your route? Your issue looks slightly different from this one (passive autoRenew vs active autoRenew), do you mind to start a new issue with reproduction steps?

The error you saw is for local development only. It popups due to some internal logic is calling tokenManager.add, we may consider revise/remove this warning message in the next major version.
