### ISSUE TITLE
Getting access_token and id_token from sessionToken - Redirect Issue

### ISSUE THREAD

**Issue by vishnup95** [okta/okta-auth-js#847] opened 2021-06-29 18:29 UTC
Hi, 

I am using okta-angular, but mainly relying on the okta API for user creation and authentication. So I thought I would post this here. 
 - I initially called the `sigInWithCredentials` method to sign users into my Angular app. 
 - Since we have enabled SMS-based MFA for users. I get `MFA_REQUIRED`. I call the `factors. verify()` method to send out an SMS and show a screen to enter the token received in SMS to the users. All this is happening within the app. 
 - After the user enters the MFA, I call the verify method with `passCode: "TOKEN_RECIEVED"`. 
 - The response is a session token and other details. https://developer.okta.com/docs/reference/api/authn/#response-example-for-verify-sms-challenge-otp
 - I then need to get a Bearer access token. I call the `token.getWithRedirect({sessionToken})` and use the `token.parseFromUrl()` method to store the access token to the tokenManager. 
 
## The Problem 

When I call the `getWithRedirect` method, I actually end up on an okta org page asking me to enter the MFA token again.   

![screengrab_okta](https://user-images.githubusercontent.com/50899727/123848762-b2ba9b00-d935-11eb-8fcc-b87125cc81ba.png)

How can I prevent this? I tried things like `prompt:none` but then it just returns me an error of `The client specified not to prompt, but the client app requires re-authentication or MFA`.

I don't understand that. Isn't the client already authenticated. Isn't that what the sessionToken represents. 

Any help would be greatly appreciated. I am desperate.

**Comment by vishnup95** [comment] 2021-06-29 18:33
I am on ` "@okta/okta-angular": "3.1.0"`

**Comment by arvindkrishnakumar-okta** [comment] 2021-06-29 18:35
@vishnup95 Thanks for posting!

@aarongranick-okta @shuowu-okta Can you assist with this please?

**Comment by shuowu** [comment] 2021-07-15 15:42
@vishnup95 Can you try `signInWithRedirect({ sessionToken })`? 

See details [here](https://github.com/okta/okta-auth-js#signinwithredirectoptions)

**Comment by shuowu** [comment] 2021-07-15 17:47
right, only use the signInWithRedirect method after you get sessionToken.

The 404 might because you have multiple okta sessions in browser (logged in with different accounts), try use incognito mode with your browser.

**Comment by vishnup95** [comment] 2021-07-16 10:37
@shuowu `getWithRedirect` also takes me to the okta page. The issue still persists.

**Comment by shuowu** [comment] 2021-07-19 20:43
@vishnup95 Sorry, I might miss guide you with the incorrect method. Please try with [session.setCookieAndRedirect](https://github.com/okta/okta-auth-js#sessionsetcookieandredirectsessiontoken-redirecturi)

We also have a sample for it, see [here](https://github.com/okta/okta-auth-js/blob/c5ae1eb0869f10f42ad8df0591db2b45c2e27c40/samples/generated/static-spa/public/app.js#L309).

**Comment by vishnup95** [comment] 2021-07-20 14:30
Thanks for that @shuowu. So I would get my `sessionToken` and call `session.setCookieAndRedirect`. Then if my understanding is correct, I need to parse from the redirect URL again right to get the tokens I need? Am I missing something?

**Comment by shuowu-okta** [comment] 2021-07-20 15:25
In your flow, two things should be done, which are get tokens and set session cookie. Before I thought both are handled within `signInWithRedirect`, but looks like it's not.

So after you get the `sessionToken`, you can firstly call [getWithoutPrompt](https://github.com/okta/okta-auth-js#tokengetwithoutpromptoptions) to get tokens and storage it with TokenManager (there is code sample in the link). After that, you can call `session.setCookieAndRedirect` to setup sso session cookie, so the MFA form will not prompt again.

**Comment by vishnup95** [comment] 2021-07-21 18:45
HI @shuowu or @shuowu-okta :slightly_smiling_face: I tried your suggestion. I went ahead and called `getWithoutPrompt` passing my sessionToken to get the authToken. After that I called the `session.setCookieAndRedirect` method. It took me to our okta page for sign in (not MFA :smile: ). 
![okta_sigin](https://user-images.githubusercontent.com/50899727/126541712-67efb63e-c27e-4ef4-936c-59a29108a353.png)
Also, the URL changed to (I ran decodeURI before posting here.), 
`https://{okta_domain}login/login.htm?fromURI=/login/sessionCookieRedirect?checkAccountSetupComplete=true&token=20111rKb-WD-yv7e6twWmH1-xKJzUvEAZPuNZLDHXV7HrbcWmLpEcZD&redirectUrl=http://localhost:4200/login`

**Comment by shuowu** [comment] 2021-07-28 20:25
@vishnup95 This issue (https://github.com/okta/okta-auth-js/issues/877) might be related to your case.

**Comment by shuowu** [comment] 2021-07-28 20:28
@vishnup95 We have identified an issue that sessionCookieRedirect is not setting "sid" cookie. I think it might related to your scenario. I'll post update here when the issue is addressed.

**Comment by shuowu** [comment] 2021-08-12 00:38
@vishnup95 We have identified the issue and released a new version. Please try with version 5.3.1, closing this issue, feel free to re-open it if the issue still exist.

**Closed by shuowu** 2021-08-12 00:38 UTC

**Comment by Shrirang97** [comment] 2021-08-24 11:15
@vishnup95 Can you tell me how you are verifying OTP/ MFA_challnge?

My scenario: Front End App calls backend service which uses `okta-auth-js` library for sending and verifying OTP.

1. On the front end app, the user click on send OTP. 
2. Front end call `sendOTP` endpoint of backend service
3. Backend service calls verify method to send OTP to user's  mobile and return `stateToken` & `factorId` to front end app
4. User gets a screen to enter OTP on front end app and clicks on verify
5. Front end app send `stateToken`, `factorId` & `passCode` i.e. OTP to backend service
**6. Backend service verifies OTP/passcode and return sessionToken to front end**

I am facing the issue of how to call `verify` method?

**Comment by Shrirang97** [comment] 2021-08-24 14:29
@vishnup95 But I need authTransaction object to call verify method How do I get that?

**Comment by shuowu** [comment] 2021-08-24 14:45
@Shrirang97 If you are using okta-auth-js in your backend service for MFA purpose, then you will need to preserve the intermediate authTransaction, and use it to call the `verify` function.

**Comment by vishnup95** [comment] 2021-08-24 14:49
@Shrirang97 Like @shuowu said. You will need to persist the response of the signin call. I handled all this in the FE so that I could use some sort of state management to achieve this.

**Comment by Shrirang97** [comment] 2021-08-24 14:53
@shuowu Ok. I think that is not possible in my API to keep authTransaction state as my API has two different independent endpoint one for send-otp & one for verify-otp. I was able to do that using http call previously. This library is for front end application mostly not for backend service.

Okta team should add methods for each independent endpoint in okat-auth-js library. I can call verify OTP auth endpoint via axios call.
