### ISSUE TITLE
React Router errors starting in @okta/okta-auth-js 2.6.0 

### ISSUE THREAD

**Issue by jsNinjaneer** [okta/okta-auth-js#219] opened 2019-06-12 17:04 UTC
Something happened between @okta/okta-auth-js 2.5.0 and 2.6.0 that prevents my application from authenticating. 

I am using the following 
`const setAccessTokens = (setError, setTimeoutWarningActive) => {
  const authTokens = { accessToken: '', idToken: '' }
  authClient.tokenManager
    .get('token')
    .then(token => {
      if (token) {
        authTokens.accessToken = token.accessToken
        setAccessToken(authTokens.accessToken)
      } else if (window.location.hash.indexOf('token=') !== -1) {
        authClient.token
          .parseFromUrl()
          .then(tokens => {
            if (tokens && tokens[0]) {
              authClient.tokenManager.add('token', tokens[0])
              authTokens.accessToken = tokens[0]
              setAccessToken(authTokens.accessToken)
            }
            if (tokens && tokens[1]) {
              authClient.tokenManager.add('id_token', tokens[1])
              authTokens.idToken = tokens[1]
              setIdToken(authTokens.idToken)
            }
          })
          .catch(err => console && console.error && console.error('Error parsing URL: ', err))
      } else {
        authClient.token.getWithRedirect({
          responseType: authCredentials.responseType,
          scopes: authCredentials.scopes,
        })
      }
    })
    .catch(err => console && console.error && console.error('Login error: ', err))
}`

I am able to get to the Okta login screen to log in, however the return url is no longer being parsed. The return email is in the following format:
`http://localhost:3000/#/id_token=eyJraWQiOi[...]&access_token=eyJraWQiOiJM[...]&token_type=Bearer&expires_in=43200&scope=[...]&state=[...]`

And I am getting these errors:
Unable to retrieve OAuth redirect params cookie
Unable to parse OAuth flow response: id_token was not returned.

This code works against 2.5.0.

**Comment by snackycracky** [comment] 2019-06-16 21:13
I am stuck on the error: `Unable to retrieve OAuth redirect params cookie` as well. The cookie entry seems to be gone when renewing the token in the iframe. It's deleted in `parseFromUrl` of `token.js` and never recreated as in `getWithRedirect`.

**Comment by swiftone** [comment] 2019-06-19 21:22
@snackycracky - Thanks for the bug report!

We have a bug fix in the upcoming 2.6.1 - this is a regression related to the token name.

**Comment by dchem** [comment] 2019-09-23 04:07
Just an update, I'm still experiencing this in `2.8.0`

**Comment by swiftone** [comment] 2019-09-25 21:19
Closing as 2.6.1 was released quite a while ago.

**Closed by swiftone** 2019-09-25 21:19 UTC
Labels: bug, priority-high
